spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/androidbase
    username: root
    password: ztjztj120
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0